### ISSUE TITLE
Please upgrade the AGP version

### ISSUE THREAD

**Issue by Melendez1209** [Knightwood/ComposePreference#1]
![image](https://github.com/user-attachments/assets/eeee561a-cc08-42e3-9eca-5335eb0c3bdc)
so sorry about that I'm using the version 8.11.1
it isn't your program

**Comment by Melendez1209** [comment]
May I help u with this? but honestly i'm not good at package development😂

**Comment by Knightwood** [comment]
没什么特别限制，欢迎提交代码。

**Comment by Melendez1209** [comment]
sorry I tried to do that, but there's a big difference between our development environment, so please help

**Comment by Melendez1209** [comment]
I have solved the problem, thanks.
